### ISSUE TITLE
Add lichess-worstfish as the external engine

### ISSUE THREAD

**Issue by hindia420** [0mlml/chesshook#12]
Can you please help integrate or manually add lichess-worstfish as the external engine? I can't figure it out since worstfish doesn't have a standalone binary.

**Comment by 0mlml** [comment]
I don't plan to somehow interface with Lichess as of now, especially in this way. I have a repository where I tried to recreate Worstfish by modifying Stockfish 12 (iirc the last version before the neural network implementation) [here](https://github.com/0mlml/Worstfish)
