### ISSUE TITLE
Only shows arrows, no window rendered even after alt k

### ISSUE THREAD

**Issue by Sciccorz** [0mlml/chesshook#14]
Checked to make sure keys worked, tried tampermonkey and violent monkey, cleared local storage, relaunched browser, checked dev mode, can't seem to get it to load. Help

**Comment by 0mlml** [comment]
Might be the blatant error I pushed in the last update that caused the script to error. Should be fixed in https://github.com/0mlml/chesshook/commit/3f74500de48c3299a000aad3e3178c0584a6f455

**Comment by Sciccorz** [comment]
Yep works now. Btw how would I get it the external engine to work w stockfish 16/15?

**Comment by Sciccorz** [comment]
Also for some reason nothing works now, I can open the window but not even the arrows show up anymore

**Comment by 0mlml** [comment]
Should actually work now (https://github.com/0mlml/chesshook/commit/40961b5767969965d0d06eb8abfd006591c72e0a).

https://github.com/0mlml/chesshook/issues/2 lists how to use an external engine, but here it is again:
1. Download [stockfish](https://stockfishchess.org/download/) and  [chesshook-intermediary](https://github.com/0mlml/chesshook-intermediary) - Put them all in the same folder
2. Download and install [Go](https://go.dev/dl/)
3. Compile the program by executing `go build .` in the downloaded repo which should produce `./chesshook-intermediary.exe` or `./chesshook-intermediary` based on your OS
4. Execute the server using `./chesshook-intermediary -engine "./stockfish"`, but make sure `./stockfish` is the actual path to stockfish
5. On the userscript side, set your config to the following - should work if the server is on the same computer:
![image](https://github.com/user-attachments/assets/9dda6bfc-9b26-40eb-bf4f-31b994e4867c)
*Note that the URL is `ws://localhost:8080/ws`, which should be default*

**Comment by Sciccorz** [comment]
Do I put the entire stockfish folder or just the exe in the same folder as the chesshook intermediary?

**Comment by 0mlml** [comment]
You should put the stockfish executable in the same folder. The command should be `./chesshook-intermediary -engine "./stockfish-windows-x86-64-avx2.exe"` with the latest windows version of stockfish

**Comment by Sciccorz** [comment]
ok i got it all working just how do i adjust some of the engine settings? 
![image](https://github.com/user-attachments/assets/b1adbbbf-8bb5-4b9b-b196-6137c477c0d3)
i get this error when i try before running it and if i try to do the same but after running the line u sent it doesnt let me type anything

**Comment by Sciccorz** [comment]
basically how do i run any of the command line flags

**Comment by Sciccorz** [comment]
btw the auto queue isnt working, its just a neverending search for new game

**Comment by 0mlml** [comment]
The command line arguments (prefixed by `-`) get passed while you run the command, and you replace `<string>` with your arguments, so your final command to run stockfish while setting the skill level to 20 and the threads to 10 would look like: 
`./chesshook-intermediary -engine "./stockfish-windows-x86-64-avx2.exe" -uciargs "setoption name Skill Level value 20;setoption name Threads value 10"`

In regards to auto queue, the auto queue feature just clicks the tab to search for a new game and then the button to start searching. The infinite queue is likely not related to the script.

**Comment by Sciccorz** [comment]
Is there a max skill level?

**Comment by 0mlml** [comment]
IIRC it's 20 for stockfish.
