### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by Sciccorz** [0mlml/chesshook#15]
![image](https://github.com/user-attachments/assets/236e4172-111b-4afa-af42-a67954638b26)
changed to new port bc using the 8080 already. checked console and external menus and nothing there. no moves showing up. y is this happening

**Comment by Sciccorz** [comment]
changed to a diff port

**Comment by 0mlml** [comment]
Glad you figured it out. Ports below 1024 generally will cause conflicts. 
8080 is a pretty common port to use so I'll consider changing the port to something else.
