### ISSUE TITLE
Using an external UCI-compliant engine with the userscript

### ISSUE THREAD

**Issue by imworkinonmyclone** [0mlml/chesshook#2]
Hey there. Is there a way to add the Maia chess net to your extention? 
Thank you

**Comment by 0mlml** [comment]
I briefly looked over the quickstart instructions for Maia Chess and lc0 to write the following, and I haven't tested anything, so I can't be sure if it works, but:
1. Download [lc0](https://lczero.org/play/quickstart/), [maia-chess](https://github.com/CSSLab/maia-chess#readme), and  [chesshook-intermediary](https://github.com/0mlml/chesshook-intermediary) - Put them all in the same folder
2. Download and install [Go](https://go.dev/dl/)
3. Compile the program by executing `go build .` in the downloaded repo which should produce `./chesshook-intermediary.exe` or ./chesshook-intermediary` based on your OS
4. Execute the server using `./chesshook-intermediary -engine "./lc0 --weights=maia-1100.pb.gz"` - I never considered passing command line flags to the engine when writing the server but looking over the code it should work
5. On the userscript side, set your config to the following - should work if the server is on the same computer:
![image](https://github.com/0mlml/chesshook/assets/63015852/7b588d11-9029-46b0-85bb-a189efc15c11)

For future reference: The "go nodes 1" in compliance with the instructions given on the maia-chess repo. Other engines will benefit from the "External Engine Auto Go Command" being checked, as that will give the engine the clock state.

**Comment by 0mlml** [comment]
I tried this method of getting the engine to work and no surprise, had issues with passing command line arguments to the engine. It's now [fixed](https://github.com/0mlml/chesshook-intermediary/commit/627929880c05104bd66061aaa090b7617a721691). I can confirm these steps to work on windows with the latest version of the intermediary server.

**Comment by imworkinonmyclone** [comment]
That is exellent. You the man!
