### ISSUE TITLE
Hotkey to hide/show arrows in case if you don't need them

### ISSUE THREAD

**Issue by kusayuzayushko** [0mlml/chesshook#3]
As an "emergency" mode or simply because some don't need them arrows all the time.

**Comment by 0mlml** [comment]
Will implement when I figure out an elegant way to create 'hotkey' config elements.

**Comment by 0mlml** [comment]
Implemented in https://github.com/0mlml/chesshook/commit/ffa911e9b91dd8bf707ebdd207dbcc986afc7229 as "Clear Arrows Hotkey".
